config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { in: 4..30 }, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :password, length: { in: 6..16 }, presence: true
  validates :username, length: { in: 4..12 }, presence: true, uniqueness: { case_sensitive: false }
  # only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy


  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="primary-header">
      <h1 class="logo">Members Only</h1>
      <nav class="navbar">
        <ul class="nav-items">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.username, edit_user_registration_path, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link"  %>
            </li>
						<li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"  %>
            </li>
            <% end %>
        </ul>
      </nav>
    </header>

    <section class = "main-section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @post do |form| %>
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title %>
    <br><br>
    <%= form.label :body, "Body:"%>
    <%= form.text_area :body, placeholder: "Body goes here"  %>
    <br><br>
    <%= form.submit "Create" %>
  <% end %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<button class="nav-button">
  <%= link_to 'Show', @post %>
</button>

<button class="nav-button">
  <%= link_to 'Back', posts_path %>
</button>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<p class="summary-text">
  The purpose of this website is to demonstrate different functionality depending on whether or not the user is logged in. If you are not logged in, you are unable to see the authors of the blog posts. However, if you sign in, you are able to create new posts, edit your own posts and view the authors of all posts.
<p>

<h1 class="page-header">Posts</h1>




<section class="posts-container">
  <%= link_to 'New Post', new_post_path, class:"new-post" %>
<% @posts.each do |post| %>
  <div class="post-container">
    <h3><%= link_to post.title, post, class:"post-link" %></h3>
    <h5>
      <% if user_signed_in? %>
        Author: 
        <% if post.user.username == current_user.username %>
          You
        <% else %>
          <%= post.user.username %>
        <% end %>
      <% else %>
        Secret Author
      <% end %>
    </h5>
    <p><%= post.body %></p>
    <table>
        <tr>
          <% if user_signed_in? %>
            <% if post.user.username == current_user.username %>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </tr>
    </table>
  </div>
<% end %>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @post.title %> </h1>
<h2>
  Author:
      <% if user_signed_in? %>
        <% if @post.user.username == current_user.username %>
          You
        <% else %>
          <%= @post.user.username %>
        <% end %>
      <% else %>
        Secret Author
      <% end %>
</h2>
<% unless user_signed_in? %>
  <h5>Sign in to view the author of this post.</h5>
<% end %>



<p> <%= @post.body %> </p>



<% if user_signed_in? %>
  <% if @post.user.username == current_user.username %>
    <button class="nav-button">
      <%= link_to 'Edit', edit_post_path(@post) %> 
    </button>
  <% end %>
<% end %>
<button class="nav-button">
  <%= link_to 'Back', posts_path %>
</button>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @user do |form| %>
    <%= form.label :username, "Username:" %>
    <%= form.text_field :username %>
    <br><br>
    <%= form.label :email, "Email:"%>
    <%= form.email_field :email, placeholder: "youremail@email.com"  %>
    <br><br>
    <%= form.label :password, "Password:" %>
    <%= form.password_field :password, placeholder: "*******" %>
    <br><br>
    <%= form.submit "Create" %>
  <% end %>

  <!-- 
  <div class="actions">
    <%= form.submit %>
  </div> 
  -->
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Username: <%= @user.username %></h1>

<p>email: <%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h2>User's Posts<p>

    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>